routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home');
    }
    else {
        return view('welcome');
    }
})->name('first');

Auth::routes();

Route::get('info/privacy', 'InfoController@privacy')->name('info.privacy');
Route::get('info/gdxp', 'InfoController@gdxp')->name('info.gdxp');
Route::get('listini/{slug}/{id}', 'SupplierController@landing')->name('supplier.landing');
Route::get('file/{id}/{type}', 'SupplierController@file')->name('supplier.file');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('supplier', 'SupplierController');
    Route::resource('subject', 'SubjectController');
    Route::resource('pact', 'PactController');
    Route::resource('order', 'OrderController');

    Route::get('supplier/{id}/products', 'SupplierController@products')->name('supplier.products');
    Route::post('supplier/{id}/products', 'SupplierController@saveProducts')->name('supplier.products.save');
    Route::post('supplier/{id}/products/import', 'SupplierController@importProducts')->name('supplier.products.import');
    Route::get('supplier/products/import/sample', 'SupplierController@importProductsSample')->name('supplier.products.import.sample');

    Route::put('order/mapzip/read', 'OrderController@mapZip')->name('order.mapzip.read');
    Route::post('order/mapzip/save', 'OrderController@realMapZip')->name('order.mapzip.save');

    Route::get('api/preferred/units', 'InfoController@preferredUnits')->name('preferred.units');
    Route::get('api/preferred/categories', 'InfoController@preferredCategories')->name('preferred.categories');

    Route::middleware(['admin'])->group(function () {
        Route::get('home/update', 'HomeController@update')->name('home.update');
        Route::get('orders/details/{id}', 'OrderController@details')->name('order.details');
        Route::get('orders/details/{id}/{format}', 'OrderController@detailsDownload')->name('order.details.download');
        Route::resource('user', 'UserController');
        Route::resource('client', 'ClientController');
    });
});

resources/views/clients.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Client</div>

                <div class="card-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active async-modal" data-modal-url="{{ route('client.create') }}">
                            Crea Nuovo Client
                        </a>

                        @foreach($clients as $client)
                            <a href="#" class="list-group-item list-group-item-action async-modal"  data-modal-url="{{ route('client.edit', $client->id) }}">
                                {{ $client->name }}
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/des.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Patti</div>

                <div class="card-body">
                    <div class="list-group">
                        @foreach($currentuser->accessiblePacts() as $pact)
                            <a href="#" class="list-group-item list-group-item-action async-modal"  data-modal-url="{{ route('pact.edit', $pact->id) }}">
                                {{ $pact->name }}
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Ordini e Prenotazioni</div>

                <div class="card-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active async-modal" data-modal-url="{{ route('order.create') }}">
                            Crea Nuovo Ordine
                        </a>

                        @foreach($currentuser->accessibleOrders() as $order)
                            <a href="#" class="list-group-item list-group-item-action async-modal" data-modal-url="{{ route('order.edit', $order->id) }}">
                                {{ join(' - ', $order->pacts->reduce(function($carry, $item) { return array_merge($carry, [$item->name]); }, [])) }}
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    @if(Session::has('feedback'))
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-info">{{ Session::get('feedback') }}</div>
            </div>
        </div>

        <hr>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-12">
            <a class="btn btn-info" href="{{ route('home.update') }}">Aggiorna riferimenti da Economia Solidale</a>
        </div>
    </div>

    <hr>

    <div class="row justify-content-center">
        @include('supplier.column')
        @include('subject.column')
        @include('pact.column')
        @include('order.column')
    </div>
</div>
@endsection

resources/views/supplier.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="list-group">
                        @foreach($currentuser->accessibleSuppliers() as $supplier)
                            <div class="list-group-item">
                                <x-larastrap::btngroup orientation="vertical" classes="float-end w-50">
                                    <a href="#" class="btn btn-outline-success async-modal" data-modal-url="{{ route('supplier.edit', $supplier->id) }}">Modifica Informazioni</a>
                                    <a href="{{ route('supplier.products', $supplier->id) }}" class="btn btn-outline-success">Aggiorna il Listino</a>
                                    @if($supplier->gdxpLastUpdate())
                                        <a href="{{ route('supplier.file', ['id' => $supplier->id, 'type' => 'csv']) }}" class="btn btn-outline-success">Scarica Listino CSV</a>
                                        <a href="{{ route('supplier.file', ['id' => $supplier->id, 'type' => 'gdxp']) }}" class="btn btn-outline-success">Scarica Listino GDXP</a>
                                    @endif
                                    <a href="{{ $supplier->getLandingUrl() }}" class="btn btn-outline-success" target="_blank">Visita la pagina pubblica</a>
                                </x-larastrap::btngroup>

                                {{ $supplier->name }}<br>
                                <small>Ultimo aggiornamento: {{ $supplier->gdxpLastUpdateHuman() }}</small>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Utenti</div>

                <div class="card-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active async-modal" data-modal-url="{{ route('user.create') }}">
                            Crea Nuovo Utente
                        </a>

                        @foreach($users as $user)
                            <a href="#" class="list-group-item list-group-item-action async-modal"  data-modal-url="{{ route('user.edit', $user->id) }}">
                                {{ $user->email }}
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection