routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home');
    }
    else {
        return view('welcome');
    }
})->name('first');

Auth::routes();

Route::get('info/privacy', 'InfoController@privacy')->name('info.privacy');
Route::get('info/gdxp', 'InfoController@gdxp')->name('info.gdxp');
Route::get('listini/{slug}/{id}', 'SupplierController@landing')->name('supplier.landing');
Route::get('file/{id}/{type}', 'SupplierController@file')->name('supplier.file');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('supplier', 'SupplierController');
    Route::resource('subject', 'SubjectController');
    Route::resource('pact', 'PactController');
    Route::resource('order', 'OrderController');

    Route::get('supplier/{id}/products', 'SupplierController@products')->name('supplier.products');
    Route::post('supplier/{id}/products', 'SupplierController@saveProducts')->name('supplier.products.save');
    Route::post('supplier/{id}/products/import', 'SupplierController@importProducts')->name('supplier.products.import');
    Route::get('supplier/products/import/sample', 'SupplierController@importProductsSample')->name('supplier.products.import.sample');

    Route::put('order/mapzip/read', 'OrderController@mapZip')->name('order.mapzip.read');
    Route::post('order/mapzip/save', 'OrderController@realMapZip')->name('order.mapzip.save');

    Route::get('api/preferred/units', 'InfoController@preferredUnits')->name('preferred.units');
    Route::get('api/preferred/categories', 'InfoController@preferredCategories')->name('preferred.categories');

    Route::middleware(['admin'])->group(function () {
        Route::get('home/update', 'HomeController@update')->name('home.update');
        Route::get('orders/details/{id}', 'OrderController@details')->name('order.details');
        Route::get('orders/details/{id}/{format}', 'OrderController@detailsDownload')->name('order.details.download');
        Route::resource('user', 'UserController');
        Route::resource('client', 'ClientController');
    });
});

app/Pact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pact extends Model
{
    public function suppliers()
    {
        return $this->belongsToMany('App\Supplier');
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Subject');
    }
}

app/Http/Controllers/PactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Pact;

class PactController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Pact::class, 'pact');
    }

    private function commonSave($pact, $request)
    {
        $pact->name = $request->input('name');

        if ($pact->exists == false) {
            $pact->uuid = (string) Str::uuid();
        }

        $pact->save();

        $pact->suppliers()->sync($request->input('suppliers', []));
        $pact->subjects()->sync($request->input('subjects', []));
    }

    public function edit(Pact $pact)
    {
        return view('pact.modal', ['pact' => $pact]);
    }

    public function update(Request $request, Pact $pact)
    {
        $this->commonSave($pact, $request);
        return redirect()->route('home');
    }
}

resources/views/pact/column.blade.php
<div class="col">
    <div class="card">
        <div class="card-header">Patti</div>

        <div class="card-body">
            <div class="list-group">
                @foreach($currentuser->accessiblePacts() as $pact)
                    <a href="#" class="list-group-item list-group-item-action async-modal"  data-modal-url="{{ route('pact.edit', $pact->id) }}">
                        {{ $pact->name }}
                    </a>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/pact/modal.blade.php
<x-larastrap::modal size="lg">
    <x-larastrap::form :method="$pact ? 'PUT' : 'POST'" :action="$pact ? route('pact.update', $pact->id) : route('pact.store')" :obj="$pact">
        <x-larastrap::text name="name" label="Nome" required />

        <hr>

        <div class="form-group row">
            <div class="col-sm-6">
                <h4>
                    Fornitori
                </h4>

                @foreach($currentuser->accessibleSuppliers() as $supplier)
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="suppliers[]" value="{{ $supplier->id }}" id="supplier-{{ $supplier->id }}" {{ $pact && $pact->suppliers()->where('supplier_id', $supplier->id)->count() != 0 ? 'checked' : '' }}>
                        <label class="form-check-label" for="supplier-{{ $supplier->id }}">{{ $supplier->name }}</label>
                    </div>
                @endforeach
            </div>

            <div class="col-sm-6">
                <h4>
                    Soggetti
                </h4>

                <?php

                function recursiveSubjects($subjects, $deep, $pact, $checked)
                {
                    $offset = join('', array_fill(0, $deep, '&nbsp;'));

                    foreach($subjects as $s) {
                        $s_checked = ($checked || ($pact && $pact->subjects()->where('subject_id', $s->id)->count() != 0));

                        echo '<div class="form-check">
                            <input class="form-check-input" type="checkbox" name="subjects[]" value="' . $s->id . '" id="subject-' . $s->id . '" ' . ($s_checked ? 'checked' : '') . '>
                            <label class="form-check-label" for="subject-' . $s->id . '">' . $offset . $s->name . '</label>
                        </div>';

                        recursiveSubjects($s->children, $deep + 3, $pact, $s_checked);
                    }
                }

                recursiveSubjects(App\Subject::where('parent_id', 0)->orderBy('name', 'asc')->get(), 0, $pact, false);

                ?>
            </div>
        </div>
    </x-larastrap::form>
</x-larastrap::modal>