routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home');
    }
    else {
        return view('welcome');
    }
})->name('first');

Auth::routes();

Route::get('info/privacy', 'InfoController@privacy')->name('info.privacy');
Route::get('info/gdxp', 'InfoController@gdxp')->name('info.gdxp');
Route::get('listini/{slug}/{id}', 'SupplierController@landing')->name('supplier.landing');
Route::get('file/{id}/{type}', 'SupplierController@file')->name('supplier.file');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('supplier', 'SupplierController');
    Route::resource('subject', 'SubjectController');
    Route::resource('pact', 'PactController');
    Route::resource('order', 'OrderController');

    Route::get('supplier/{id}/products', 'SupplierController@products')->name('supplier.products');
    Route::post('supplier/{id}/products', 'SupplierController@saveProducts')->name('supplier.products.save');
    Route::post('supplier/{id}/products/import', 'SupplierController@importProducts')->name('supplier.products.import');
    Route::get('supplier/products/import/sample', 'SupplierController@importProductsSample')->name('supplier.products.import.sample');

    Route::put('order/mapzip/read', 'OrderController@mapZip')->name('order.mapzip.read');
    Route::post('order/mapzip/save', 'OrderController@realMapZip')->name('order.mapzip.save');

    Route::get('api/preferred/units', 'InfoController@preferredUnits')->name('preferred.units');
    Route::get('api/preferred/categories', 'InfoController@preferredCategories')->name('preferred.categories');

    Route::middleware(['admin'])->group(function () {
        Route::get('home/update', 'HomeController@update')->name('home.update');
        Route::get('orders/details/{id}', 'OrderController@details')->name('order.details');
        Route::get('orders/details/{id}/{format}', 'OrderController@detailsDownload')->name('order.details.download');
        Route::resource('user', 'UserController');
        Route::resource('client', 'ClientController');
    });
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;

class Supplier extends Model
{
    public function gdxpPath()
    {
        /*
            Se sto accedendo al file GDXP di un fornitore correlato ad un
            ordine, do precedenza al listino caricato in tale contesto
        */
        if (isset($this->pivot->products_file) && filled($this->pivot->products_file)) {
            $attribute = $this->pivot->products_file;
        }
        else {
            $attribute = $this->products_file;
        }

        if (filled($attribute)) {
            $path = storage_path('app/' . $attribute);
            if (file_exists($path)) {
                return $path;
            }
        }

        return null;
    }

    public function getLocalityAttribute()
    {
        $path = $this->gdxpPath();
        if ($path) {
            $contents = json_decode(file_get_contents($path));
            return $contents->blocks[0]->supplier->address->locality ?? '';
        }
        else {
            return '';
        }
    }

    public function gdxpLastUpdate()
    {
        $path = $this->gdxpPath();
        if ($path) {
            $contents = json_decode(file_get_contents($path));
            if (isset($contents->creationDate) && preg_match('/[0-9]{4,4}-[0-9]{1,2}-[0-9]{1,2}/', $contents->creationDate)) {
                return strtotime($contents->creationDate);
            }
            else {
                return filemtime($path);
            }
        }
        else {
            return null;
        }
    }

    public function gdxpLastUpdateHuman()
    {
        $last = $this->gdxpLastUpdate();
        if ($last) {
            return date('d/m/Y', $last);
        }
        else {
            return 'Mai';
        }
    }

    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    public function pacts()
    {
        return $this->belongsToMany('App\Pact');
    }

    public static function getRand()
    {
        $test = 0;

        while($test < 10) {
            $supplier = self::where('products_file', '!=', '')->inRandomOrder()->first();
            if ($supplier && $supplier->gdxpPath()) {
                break;
            }

            $test++;
            $supplier = null;
        }

        return $supplier;
    }

    public function getLandingUrl()
    {
        return route('supplier.landing', ['slug' => Str::slug($this->name), 'id' => $this->id]);
    }

    public function saveGdxp($gdxp)
    {
        $path = 'gdxp/' . Str::random(40) . '.txt';
        $fullpath = storage_path('app/' . $path);
        file_put_contents($fullpath, json_encode($gdxp));
        $this->products_file = $path;
        $this->save();
    }

    /*
        Funzione di comodo per appiattire i contenuti formattati nel GDXP in
        oggetti più facilmente gestibili nel form di edit del listino.
        Non salvare un fornitore dopo aver eseguito questa funzione.
    */
    public function fromGdxp($data)
    {
        if ($data) {
            $this->taxCode = $data->blocks[0]->supplier->taxCode ?? '';
            $this->vatNumber = $data->blocks[0]->supplier->vatNumber ?? '';
            $this->contacts = $data->blocks[0]->supplier->contacts ?? [];
            $this->street = $data->blocks[0]->supplier->address->street ?? '';
            $this->locality = $data->blocks[0]->supplier->address->locality ?? '';
            $this->zipCode = $data->blocks[0]->supplier->address->zipCode ?? '';

            $products = [];

            foreach($data->blocks[0]->supplier->products as $product) {
                $product->um = $product->um ?? '';
                $product->category = $product->category ?? '';
                $product->packageQty = $product->orderInfo->packageQty ?? '';
                $product->umPrice = $product->orderInfo->umPrice ?? '';
                $product->maxQty = $product->orderInfo->maxQty ?? '';
                $product->minQty = $product->orderInfo->minQty ?? '';
                $product->mulQty = $product->orderInfo->mulQty ?? '';
                $product->availableQty = $product->orderInfo->availableQty ?? '';
                $product->vatRate = $product->orderInfo->vatRate ?? '';

                $products[] = $product;
            }

            $this->products = $products;
        }
        else {
            $this->products = [];
        }
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use Log;
use Cache;
use Session;
use Response;

use App\Helpers\GDXP;
use App\Supplier;

class SupplierController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Supplier::class, 'supplier');
    }

    private function commonSave($supplier, $request)
    {
        $supplier->name = $request->input('name');
        $supplier->vat = $request->input('vat');
        $supplier->active = $request->has('active');

        if ($request->hasFile('products_file')) {
            $supplier->products_file = $request->products_file->store('gdxp');
            $path = $supplier->gdxpPath();
            if (GDXP::test(json_decode(file_get_contents($path))) == false) {
                $supplier->products_file = '';
                Log::debug('File GDXP allegato al fornitore non valido');
                Session::flash('feedback', 'File GDXP non valido!');
            }
            else {
                Cache::forget('suppliers_list');
            }
        }
        else {
            if ($request->has('delete_file')) {
                $path = $supplier->gdxpPath();
                if ($path) {
                    unlink($path);
                }

                $supplier->products_file = '';
            }
        }

        $supplier->save();
    }

    public function edit(Request $request, Supplier $supplier)
    {
        return view('supplier.modal', ['supplier' => $supplier]);
    }

    public function update(Request $request, Supplier $supplier)
    {
        $this->commonSave($supplier, $request);
        return redirect()->route('home');
    }

    public function file(Request $request, $id, $type)
    {
        $supplier = Supplier::find($id);
        if (is_null($supplier)) {
            abort(404);
        }

        $path = $supplier->gdxpPath();
        if (is_null($path)) {
            abort(404);
        }

        if ($type == 'gdxp') {
            return response()->download($path);
        }
        else if ($type == 'csv') {
            return response()->download(GDXP::toCsv(file_get_contents($path)))->deleteFileAfterSend();
        }
        else {
            abort(404);
        }
    }

    public function products(Request $request, $id)
    {
        $user = $request->user();
        $supplier = Supplier::find($id);

        if ($user->can('update', $supplier)) {
            return view('supplier.products', ['supplier' => $supplier]);
        }
        else {
            abort(401);
        }
    }

    public function saveProducts(Request $request, $id)
    {
        $user = $request->user();
        $supplier = Supplier::find($id);

        if ($user->can('update', $supplier)) {
            $gdxp = GDXP::empty();
            $gdxp->blocks[] = json_decode($request->input('gdxp'));
            $supplier->saveGdxp($gdxp);
            Cache::forget('suppliers_list');
            Session::flash('saved', 'true');
        }
        else {
            abort(401);
        }
    }

    public function importProductsSample(Request $request)
    {
        $callback = function() {
            $file = fopen('php://output', 'w');
            $cols = array_keys(GDXP::csvColumns());
            fputcsv($file, $cols);
            fclose($file);
        };

        return Response::stream($callback, 200, [
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Content-type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename=listino_prodotti.csv',
            'Expires' => '0',
            'Pragma' => 'public'
        ]);
    }

    private function parseDecimal($value, $default = 0)
    {
        $value = trim($value);

        if (filled($value) == false) {
            return $default;
        }

        return strtr($value, ',', '.');
    }

    private function guessCsvFileSeparator($path)
    {
        $contents = fopen($path, 'r');
        if ($contents === false) {
            return null;
        }

        $separators = [',', ';', "\t"];
        $lenghts = [0, 0, 0];

        foreach($separators as $sep_index => $sep) {
            $row = fgetcsv($contents, 0, $sep);
            $lenghts[$sep_index] = count($row);
            rewind($contents);
        }

        $target_separator = $separators[array_search(max($lenghts), $lenghts)] ?? null;
        if (is_null($target_separator)) {
            throw new \Exception(_i('Impossibile interpretare il file'), 1);
        }

        return $target_separator;
    }

    public function importProducts(Request $request, $id)
    {
        $user = $request->user();
        $supplier = Supplier::find($id);

        if ($user->can('update', $supplier)) {
            $data = $supplier->gdxpPath();
            if ($data) {
                $data = json_decode(file_get_contents($data));
            }
            else {
                $data = GDXP::empty();
                $data->blocks[] = (object) [
                    'supplier' => (object) [
                        'products' => [],
                    ],
                ];
            }

            $csv_path = $request->csv->store('temp');
            $csv_path = storage_path('app/' . $csv_path);

            $separator = $this->guessCsvFileSeparator($csv_path);

            $file = fopen($csv_path, 'r');
            fgetcsv($file, null, $separator);

            while($row = fgetcsv($file, null, $separator)) {
                $new = (object) [
                    'name' => $row[0],
                    'um' => $row[2],
                    'category' => $row[3],
                    'sku' => $row[4],
                    'description' => $row[5],
                    'orderInfo' => (object) [
                        'packageQty' => $this->parseDecimal($row[6], 1),
                        'umPrice' => $this->parseDecimal($row[7]),
                        'vatRate' => $this->parseDecimal($row[8], 22),
                    ],
                    'active' => boolval($row[1]),
                ];

                $found = false;

                foreach($data->blocks[0]->supplier->products as $index => $product) {
                    if ($product->sku == $new->sku) {
                        array_splice($data->blocks[0]->supplier->products, $index, 1, [$new]);
                        $found = true;
                        break;
                    }
                }

                if ($found == false) {
                    $data->blocks[0]->supplier->products[] = $new;
                }
            }

            unlink($csv_path);

            $supplier->saveGdxp($data);
            Cache::forget('suppliers_list');
            Session::flash('saved', 'true');

            return redirect()->route('supplier.products', $supplier->id);
        }
        else {
            abort(401);
        }
    }

    public function landing(Request $request, $slug, $id)
    {
        $supplier = Supplier::find($id);
        if (is_null($supplier)) {
            return redirect()->route('home');
        }

        return view('supplier.landing', ['supplier' => $supplier]);
    }
}

resources/views/supplier/column.blade.php
<div class="col">
    <div class="card">
        <div class="card-header">
            <span class="float-end">
                <input type="checkbox" name="filter_gdxp"> Filtra GDXP
            </span>

            Fornitori
        </div>

        <div class="card-body">
            <div class="list-group">
                @foreach($currentuser->accessibleSuppliers() as $supplier)
                    <a href="#" class="list-group-item list-group-item-action async-modal"  data-modal-url="{{ route('supplier.edit', $supplier->id) }}">
                        {{ $supplier->name }}

                        @if(is_null($supplier->gdxpPath()))
                            <span class="badge bg-danger badge-pill badge-no-gdxp">NO GDXP</span>
                        @elseif($supplier->active == false)
                            <span class="badge bg-warning text-black badge-pill">NO ATTIVO</span>
                        @endif

                        @if($supplier->external_id == 0)
                            <span class="badge bg-info badge-pill">NO ES</span>
                        @endif
                    </a>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/supplier/landing.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>{{ $supplier->name }} {{ $supplier->locality ? (' - ' . $supplier->locality) : '' }}</h2>
            <h4>Ultimo aggiornamento: {{ $supplier->gdxpLastUpdateHuman() }}</h4>

            <hr>

            <p>
                Da questa pagina puoi scaricare manualmente il listino aggiornato del fornitore. Ricorda che usando <a href="{{ route('info.gdxp') }}">uno dei gestionali aderenti all'iniziativa</a> puoi ottenere i listini aggiornati in modo automatico!
            </p>
        </div>
    </div>

    <div class="row">
        @if($supplier->gdxpLastUpdate())
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">GDXP</h4>
                        <p class="card-text">Il listino in formato GDXP, importabile nei migliori gestionali per l'economia solidale. <a href="{{ route('info.gdxp') }}">Scopri di più.</a></p>
                        <a href="{{ route('supplier.file', ['id' => $supplier->id, 'type' => 'gdxp']) }}" class="btn btn-primary">Scarica File</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">CSV</h4>
                        <p class="card-text">Il listino in formato CSV, consultabile con qualsiasi applicazione per fogli di calcolo (Office Excel, LibreOffice Calc, Google Spreedsheet...).</p>
                        <a href="{{ route('supplier.file', ['id' => $supplier->id, 'type' => 'csv']) }}" class="btn btn-primary">Scarica File</a>
                    </div>
                </div>
            </div>
        @else
            <div class="col">
                <div class="alert alert-danger lead text-center">
                    Questo fornitore non ha ancora caricato il proprio listino!
                </div>
            </div>
        @endif
    </div>

    @if($supplier->external_id != 0)
        <br>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body text-center">
                        <p class="card-text"><a href="https://economiasolidale.net/node/{{ $supplier->external_id }}">Consulta la scheda di questo fornitore su economiasolidale.net</a></p>
                    </div>
                </div>
            </div>
        </div>
    @endif
</div>

@endsection

resources/views/supplier/modal.blade.php
<x-larastrap::modal size="lg">
    <x-larastrap::form :method="$supplier ? 'PUT' : POST" :action="$supplier ? route('supplier.update', $supplier->id) : route('supplier.store')" :obj="$supplier">
        <x-larastrap::text name="name" label="Nome" required />
        <x-larastrap::text name="vat" label="Partita IVA" required />
        <x-larastrap::check name="active" label="Attivo" />

        <?php

        if ($supplier && $supplier->gdxpLastUpdate()) {
            $last_update = sprintf('Ultimo aggiornamento: %s - <a href="%s" target="_blank">Scarica il File</a>', $supplier->gdxpLastUpdateHuman(), route('api.get', $supplier->vat));
        }
        else {
            $last_update = '';
        }

        ?>
        <x-larastrap::file name="products_file" label="Carica Nuovo Listino GDXP" :help="$last_update" pophelp="È possibile generare il proprio listino GDXP autonomamente e caricarlo qui per trasmetterlo automaticamente ai gestionali." />

        @if($supplier)
            @if($currentuser->role != 'supplier')
                @if($supplier->gdxpLastUpdate())
                    <x-larastrap::check name="delete_file" label="Elimina questo listino" checked="false" />
                @endif

                <x-larastrap::field label="Listino Manuale">
                    <a href="{{ route('supplier.products', $supplier->id) }}" class="btn btn-info">Modifica manuale listino</a>
                </x-larastrap::field>

                <x-larastrap::field label="Utenti Collegati">
                    @if($supplier->users->count() == 0)
                        <input type="text" readonly class="form-control-plaintext" value="Nessun utente collegato a questo fornitore">
                    @else
                        <ul>
                            @foreach($supplier->users as $user)
                                <li>{{ $user->email }}</li>
                            @endforeach
                        </ul>
                    @endif
                </x-larastrap::field>
            @endif

            @if($currentuser->role == 'supplier')
                <hr>
                <p>
                    Includi il seguente frammento di HTML nel tuo sito per rendere accessibile direttamente il tuo listino aggiornato.
                </p>
                <p>
<pre><code>&lt;a href="{{ $supplier->getLandingUrl() }}"&gt;
    &lt;img src="{{ asset('images/hub.png') }}" style="max-width: 100%"&gt;
&lt;/a&gt;</code></pre>
                </p>
            @endif
        @endif
    </x-larastrap::form>
</x-larastrap::modal>

resources/views/supplier/products.blade.php
@extends('layouts.app')

@section('content')

<?php

$data = $supplier->gdxpPath();
if ($data) {
    $data = json_decode(file_get_contents($data));
}

$supplier->fromGdxp($data);

?>

<div class="container-fluid">
    @if(Session::get('saved'))
        <div class="toast-container position-absolute mt-5 p-3 top-0 end-0" style="z-index: 2000">
            <div class="toast align-items-center" data-bs-autohide="true" data-bs-delay="3000">
                <div class="d-flex">
                    <div class="toast-body">
                        Modifiche salvate.
                    </div>
                    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    @endif

    <x-larastrap::form method="POST" :action="route('supplier.products.save', $supplier->id)" classes="gdxp-serialize" :obj="$supplier" formview="vertical">
        <div class="row">
            <div class="col-12">
                <div class="card" id="details">
                    <div class="card-header">Anagrafica</div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <x-larastrap::text name="name" label="Nome" required />
                                <x-larastrap::text name="vatNumber" label="Partita IVA" required />
                                <x-larastrap::text name="taxCode" label="Codice Fiscale" />
                            </div>

                            <div class="col">
                                <x-larastrap::field label="Indirizzo">
                                    <div class="row">
                                        <div class="col-12 mb-1">
                                            <x-larastrap::text name="street" placeholder="Indirizzo e numero civico" squeeze required />
                                        </div>
                                        <div class="col-6">
                                            <x-larastrap::text name="locality" placeholder="Città" squeeze required />
                                        </div>
                                        <div class="col-6">
                                            <x-larastrap::text name="zipCode" placeholder="CAP" squeeze required />
                                        </div>

                                        @if(empty($supplier->locality))
                                            <div class="col-12 mt-1">
                                                <small>Indicando almeno la città, sarà più semplice trovarti per i GAS vicini a te.</small>
                                            </div>
                                        @endif
                                    </div>
                                </x-larastrap::field>

                                <x-larastrap::field label="Contatti">
                                    <table class="table dynamic-table table-borderless table-sm" id="contacts">
                                        <tbody>
                                            @if($data)
                                                @foreach($supplier->contacts as $contact)
                                                    @include('supplier.partials.contact', ['contact' => $contact])
                                                @endforeach
                                            @endif

                                            <tr>
                                                <td colspan="3">
                                                    <a href="" class="btn btn-warning add-row">Aggiungi Contatto</a>
                                                    @if(empty($supplier->contacts))
                                                        <small>È consigliato aggiungere almeno un indirizzo email</small>
                                                    @endif
                                                </td>
                                            </tr>
                                        </tbody>
                                        <tfoot hidden>
                                            @include('supplier.partials.contact', ['contact' => (object)[]])
                                        </tfoot>
                                    </table>
                                </x-larastrap::field>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col text-end mt-2">
                                <button class="btn btn-success" type="submit">Salva</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-3 mb-2">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <x-larastrap::link label="Importa CSV" classes="float-end" triggers_modal="#importCSV" />
                        Prodotti
                    </div>

                    <div class="card-body">
                        <table class="table dynamic-table table-borderless" id="products">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Attivo</th>
                                    <th>Codice Univoco</th>
                                    <th>Unità di Misura</th>
                                    <th>Categoria</th>
                                    <th>Descrizione</th>
                                    <th>Prezzo Unitario</th>
                                    <th>Aliquota IVA</th>
                                    <th>Dimensione Confezione</th>
                                    <th>Totale Disponibile</th>
                                    <th>Elimina</th>
                                </tr>
                            </thead>
                            <tbody class="items">
                                @if($data)
                                    @foreach($supplier->products as $product)
                                        @include('supplier.partials.product', [
                                            'product' => $product,
                                            'fake' => false,
                                        ])
                                    @endforeach
                                @endif

                                <tr>
                                    <td colspan="10">
                                        <a href="" class="btn btn-warning add-row">Aggiungi Prodotto</a>
                                    </td>
                                </tr>
                            </tbody>
                            <tfoot hidden>
                                @include('supplier.partials.product', [
                                    'product' => (object)['active' => true],
                                    'fake' => true,
                                ])
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </x-larastrap::form>
</div>

<x-larastrap::modal size="lg" id="importCSV">
    <x-larastrap::form method="POST" :action="route('supplier.products.import', $supplier->id)">
        <p>
            Da qui è possibile importare un file CSV con le informazioni dei prodotti. <a href="{{ route('supplier.products.import.sample') }}">Clicca qui per scaricare il template di riferimento</a>, con le colonne attese nel file.
        </p>
        <ul>
            @foreach(\App\Helpers\GDXP::csvColumns() as $label => $desc)
                <li><strong>{{ $label }}</strong>: {{ $desc['explain'] }}</li>
            @endforeach
        </ul>
        <p>
            Se nel file CSV viene individuato un prodotto con lo stesso Codice Univoco di un prodotto già esistente, quest'ultimo viene sovrascritto coi nuovi parametri.
        </p>
        <p>
            Dopo l'importazione si raccomanda di scorrere la lista completa dei prodotti per verificare eventuali anomalie o errori.
        </p>

        <x-larastrap::file name="csv" label="File CSV" accepts=".csv" />
    </x-larastrap::form>
</x-larastrap::modal>

@endsection