routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home');
    }
    else {
        return view('welcome');
    }
})->name('first');

Auth::routes();

Route::get('info/privacy', 'InfoController@privacy')->name('info.privacy');
Route::get('info/gdxp', 'InfoController@gdxp')->name('info.gdxp');
Route::get('listini/{slug}/{id}', 'SupplierController@landing')->name('supplier.landing');
Route::get('file/{id}/{type}', 'SupplierController@file')->name('supplier.file');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('supplier', 'SupplierController');
    Route::resource('subject', 'SubjectController');
    Route::resource('pact', 'PactController');
    Route::resource('order', 'OrderController');

    Route::get('supplier/{id}/products', 'SupplierController@products')->name('supplier.products');
    Route::post('supplier/{id}/products', 'SupplierController@saveProducts')->name('supplier.products.save');
    Route::post('supplier/{id}/products/import', 'SupplierController@importProducts')->name('supplier.products.import');
    Route::get('supplier/products/import/sample', 'SupplierController@importProductsSample')->name('supplier.products.import.sample');

    Route::put('order/mapzip/read', 'OrderController@mapZip')->name('order.mapzip.read');
    Route::post('order/mapzip/save', 'OrderController@realMapZip')->name('order.mapzip.save');

    Route::get('api/preferred/units', 'InfoController@preferredUnits')->name('preferred.units');
    Route::get('api/preferred/categories', 'InfoController@preferredCategories')->name('preferred.categories');

    Route::middleware(['admin'])->group(function () {
        Route::get('home/update', 'HomeController@update')->name('home.update');
        Route::get('orders/details/{id}', 'OrderController@details')->name('order.details');
        Route::get('orders/details/{id}/{format}', 'OrderController@detailsDownload')->name('order.details.download');
        Route::resource('user', 'UserController');
        Route::resource('client', 'ClientController');
    });
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;
use Illuminate\Support\Collection;

class Order extends Model
{
    public function pacts()
    {
        return $this->belongsToMany('App\Pact');
    }

    public function suppliers()
    {
        return $this->belongsToMany('App\Supplier')->withPivot(['products_file']);
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Subject')->withPivot(['booking_file']);
    }

    public function humanDate($name)
    {
        list($y, $m, $d) = explode('-', $this->$name);
        return sprintf('%d/%d/%d', $d, $m, $y);
    }

    private function productIdentifier($product)
    {
        if (isset($product->global_id) && filled($product->global_id)) {
            return $product->global_id;
        }
        else if (isset($product->sku) && filled($product->sku)) {
            return $product->sku;
        }
        else {
            return Str::slug($product->name);
        }
    }

    private function supplierIdentifier($supplier)
    {
        return $supplier->vatNumber ?? ($supplier->vat ?? Str::slug($supplier->name));
    }

    public function aggregate()
    {
        $data = [];

        foreach ($this->suppliers as $supplier) {
            $gdxp_path = $supplier->gdxpPath();
            if (filled($gdxp_path)) {
                $supplier_identifier = $this->supplierIdentifier($supplier);
                $gdxp = json_decode(file_get_contents($gdxp_path));

                $s = (object) [
                    'identifier' => $supplier_identifier,
                    'name' => $supplier->name,
                    'products' => [],
                ];

                foreach($gdxp->blocks as $block) {
                    foreach($block->supplier->products as $product) {
                        $identifier = $this->productIdentifier($product);

                        $p = (object) [
                            'name' => $product->name,
                            'uuid' => $identifier,
                            'quantity' => 0,
                            'subjects' => [],
                        ];

                        $s->products[$identifier] = $p;
                    }
                }

                $data[$supplier_identifier] = $s;
            }
        }

        foreach ($this->subjects as $subject) {
            if (filled($subject->pivot->booking_file)) {
                $gdxp = json_decode(file_get_contents(storage_path('app/' . $subject->pivot->booking_file)));

                foreach($gdxp->blocks as $block) {
                    $supplier_identifier = $this->supplierIdentifier($block->supplier);
                    if (isset($data[$supplier_identifier])) {
                        foreach($block->supplier->products as $product) {
                            if (isset($product->bookingInfo)) {
                                $identifier = $this->productIdentifier($product);
                                if (isset($data[$supplier_identifier]->products[$identifier])) {
                                    $data[$supplier_identifier]->products[$identifier]->quantity += $product->bookingInfo->totalQty;

                                    $data[$supplier_identifier]->products[$identifier]->subjects[] = (object) [
                                        'name' => $subject->name,
                                        'quantity' => $product->bookingInfo->totalQty,
                                    ];
                                }
                            }
                        }
                    }
                }
            }
        }

        return $data;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use Log;
use PDF;

use JBZoo\Utils\FS;
use ezcArchive;

use App\Order;
use App\Subject;

class OrderController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Order::class, 'order');
    }

    private function parseDate($date)
    {
        if (strpos($date, '/') !== false) {
            list($d, $m, $y) = explode('/', $date);
            return sprintf('%s-%s-%s', $y, $m, $d);
        }
        else {
            return $date;
        }
    }

    private function commonSave($order, $request)
    {
        if ($order->exists == false) {
            $order->uuid = (string) Str::uuid();
        }

        $order->start = $this->parseDate($request->input('start'));
        $order->end = $this->parseDate($request->input('end'));
        $order->save();

        $order->pacts()->sync($request->input('pacts', []));

        $suppliers = $request->input('suppliers', []);
        $actual_suppliers = [];

        foreach($suppliers as $supplier_id) {
            if (!filled($supplier_id)) {
                continue;
            }

            $path = '';
            $key = 'products_file_' . $supplier_id;

            if ($request->hasFile($key)) {
                $path = $request->$key->store('gdxp');
            }
            else {
                $existing = $order->suppliers()->where('suppliers.id', $supplier_id)->first();
                if ($existing) {
                    $path = $existing->pivot->products_file;
                }
            }

            $actual_suppliers[$supplier_id] = ['products_file' => $path];
        }

        $order->suppliers()->sync($actual_suppliers);

        $subjects = $request->input('subjects', []);
        $actual_subjects = [];

        foreach($subjects as $subject_id) {
            if (!filled($subject_id)) {
                continue;
            }

            $path = '';
            $key = 'booking_file_' . $subject_id;

            if ($request->hasFile($key)) {
                $path = $request->$key->store('gdxp');
            }
            else {
                $existing = $order->subjects()->where('subjects.id', $subject_id)->first();
                if ($existing) {
                    $path = $existing->pivot->booking_file;
                }
            }

            $actual_subjects[$subject_id] = ['booking_file' => $path];
        }

        $order->subjects()->syncWithoutDetaching($actual_subjects);
    }

    public function readSubjectsZip($filepath)
    {
        $archive = ezcArchive::open($filepath);
        $temp_folder = sprintf('%s/extracted_zip_%s', sys_get_temp_dir(), Str::random(10));
        mkdir($temp_folder, 0777);

        $data = (object) [
            'zip_path' => $filepath,
            'path' => $temp_folder,
            'contents' => [],
        ];

        while ($archive->valid()) {
            $entry = $archive->current();
            $archive->extractCurrent($temp_folder);
            $temp_path = $temp_folder . '/' . $entry->getPath();

            $contents = json_decode(file_get_contents($temp_path));
            $data->contents[] = (object) [
                'name' => $contents->subject->name,
                'file' => $entry->getPath(),
            ];

            $archive->next();
        }

        return $data;
    }

    public function mapZip(Request $request)
    {
        $id = $request->input('order_id');
        $order = Order::find($id);
        $path = $request->booking_file_multiple->store('temp');
        $info = $this->readSubjectsZip(storage_path('app/' . $path));
        return view('order.mapzip', ['info' => $info, 'order' => $order, 'path' => $path]);
    }

    public function realMapZip(Request $request)
    {
        $id = $request->input('order_id');
        $order = Order::find($id);

        $original_path = $request->input('folder_path');
        $info = $this->readSubjectsZip($original_path);

        $subjects = $request->input('subjects');
        $original_filenames = $request->input('original_filename');
        $actual_subjects = [];

        foreach($subjects as $index => $subject) {
            $filename = $original_filenames[$index];
            $old_path = $info->path . '/' . $filename;

            if ($subject == 'new') {
                \Log::debug('creo');
                $s = new Subject();
                $contents = json_decode(file_get_contents($old_path));
                $s->name = $contents->subject->name;
                $s->key = (string) Str::uuid();
                $s->save();

                $subject = $s->id;
            }
            else if ($subject == 0) {
                \Log::debug('salto');
                continue;
            }

            do {
                $final_filename = Str::random(20);
                $path = storage_path('app/gdxp/' . $final_filename);
            } while(file_exists($path));

            rename($old_path, $path);
            $actual_subjects[$subject] = ['booking_file' => 'gdxp/' . $final_filename];
        }

        $order->subjects()->syncWithoutDetaching($actual_subjects);
        @unlink($original_path);
        return redirect()->route('home');
    }

    public function create()
    {
        return view('order.modal', ['order' => null]);
    }

    public function store(Request $request)
    {
        $order = new Order();
        $this->commonSave($order, $request);
        return redirect()->route('home');
    }

    public function edit(Order $order)
    {
        foreach($order->pacts as $pact) {
            foreach($pact->subjects as $subject) {
                $existing = $order->subjects()->where('subjects.id', $subject->id)->first();
                if (is_null($existing)) {
                    $order->subjects()->attach($subject->id);
                }
            }
        }

        return view('order.modal', ['order' => $order]);
    }

    public function update(Request $request, Order $order)
    {
        $this->commonSave($order, $request);
        return redirect()->route('home');
    }

    public function details($id)
    {
        $order = Order::find($id);
        return view('order.details', ['order' => $order]);
    }

    public function detailsDownload($id, $format)
    {
        $order = Order::find($id);
        $data = $order->aggregate();

        switch($format) {
            case 'pdf':
                $contents = [];
                $first_column_done = false;

                foreach($data as $supplier) {
                    foreach($supplier->products as $product) {
                        foreach($product->subjects as $index => $subject) {
                            if ($first_column_done == false) {
                                $contents[$index] = (object) [
                                    'name' => $subject->name,
                                    'products' => [],
                                ];
                            }

                            if ($subject->quantity != 0) {
                                $contents[$index]->products[] = (object) [
                                    'name' => $product->name,
                                    'quantity' => $subject->quantity,
                                ];
                            }
                        }

                        $first_column_done = true;
                    }
                }

                $last_row = (object) [
                    'name' => 'Totali'
                ];

                foreach($data as $supplier) {
                    foreach($supplier->products as $product) {
                        $last_row->products[] = (object) [
                            'name' => $product->name,
                            'quantity' => $product->quantity,
                        ];
                    }
                }

                $contents[] = $last_row;

                $pdf = PDF::loadView('order.details_pdf', ['contents' => $contents]);
                return $pdf->download('aggregato.pdf');
                break;

            case 'csv':
                $headers = ['GAS'];

                foreach($data as $supplier) {
                    foreach($supplier->products as $product) {
                        $headers[] = $product->name;
                    }
                }

                $contents = [];
                $first_column_done = false;

                foreach($data as $supplier) {
                    foreach($supplier->products as $product) {
                        foreach($product->subjects as $index => $subject) {
                            if ($first_column_done == false) {
                                $contents[$index] = [$subject->name];
                            }

                            $contents[$index][] = $subject->quantity;
                        }

                        $first_column_done = true;
                    }
                }

                $last_row = ['Totali'];

                foreach($data as $supplier) {
                    foreach($supplier->products as $product) {
                        $last_row[] = $product->quantity;
                    }
                }

                $contents[] = $last_row;

                return output_csv('aggregato.csv', $headers, $contents, null);
                break;
        }
    }
}

resources/views/order/column.blade.php
<div class="col">
    <div class="card">
        <div class="card-header">Ordini e Prenotazioni</div>

        <div class="card-body">
            <div class="list-group">
                @can('create', App\Order::class)
                    <a href="#" class="list-group-item list-group-item-action active async-modal" data-modal-url="{{ route('order.create') }}">
                        Crea Nuovo Ordine
                    </a>
                @endif

                @foreach($currentuser->accessibleOrders() as $order)
                    <a href="#" class="list-group-item list-group-item-action async-modal" data-modal-url="{{ route('order.edit', $order->id) }}">
                        {{ join(' - ', $order->pacts->reduce(function($carry, $item) { return array_merge($carry, [$item->name]); }, [])) }}
                    </a>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/order/details.blade.php
<x-larastrap::modal size="xl">
    <?php $data = $order->aggregate() ?>

    @foreach($data as $supplier)
        <h4>{{ $supplier->name }}</h4>

        @foreach($supplier->products as $product)
            <div class="row">
                <div class="col-sm-8">
                    <a class="btn btn-primary {{ $product->quantity == 0 ? 'disabled' : '' }}" data-bs-toggle="collapse" href="#product-{{ $product->uuid }}">
                        <span class="dripicons-search"></span>
                    </a>
                    {{ $product->name }}
                </div>
                <div class="col-sm-4">
                    {{ $product->quantity }}
                </div>

                <div class="col-sm-12">
                    <div class="collapse mb-3" id="product-{{ $product->uuid }}">
                        <div class="card card-body">
                            @foreach($product->subjects as $subject)
                                <div class="row">
                                    <div class="col-sm-8">
                                        {{ $subject->name }}
                                    </div>
                                    <div class="col-sm-4">
                                        {{ $subject->quantity }}
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @endforeach

    <div class="row mt-3">
        <div class="col">
            <a href="{{ route('order.details.download', ['id' => $order->id, 'format' => 'csv']) }}" class="btn btn-success">Scarica CSV</a>
            <a href="{{ route('order.details.download', ['id' => $order->id, 'format' => 'pdf']) }}" class="btn btn-success">Scarica PDF</a>
        </div>
    </div>
</x-larastrap::modal>

resources/views/order/details_pdf.blade.php
<html>
    <head>
        <style>
            table {
                border-spacing: 0;
                border-collapse: collapse;
                margin-top: 10px;
            }
        </style>
    </head>

    <body>
        @foreach($contents as $content)
            <table border="1" width="100%" cellpadding="5">
                <tr>
                    <td colspan="2" style="text-align: center">{{ $content->name }}</td>
                </tr>

                @foreach($content->products as $product)
                    <tr>
                        <td width="80%">{{ $product->name }}</td>
                        <td width="20%">{{ $product->quantity }}</td>
                    </tr>
                @endforeach
            </table>
        @endforeach
    </body>
</html>

resources/views/order/mapzip.blade.php
<x-larastrap::modal size="xl">
    <x-larastrap::form method="POST" :action="route('order.mapzip.save')">
        <p>
            Di seguito, l'elenco dei files letti dall'archivio compresso. Associa ogni file ad uno dei soggetti coinvolti nell'ordine per identificare tutti gli elementi.
        </p>

        <input type="hidden" name="folder_path" value="{{ $info->zip_path }}">
        <input type="hidden" name="order_id" value="{{ $order->id }}">

        <table class="table">
            <thead>
                <tr>
                    <th>Nome File</th>
                    <th>Nome GAS</th>
                    <th>Assegnazione</th>
                </tr>
            </thead>
            <tbody>
                @foreach($info->contents as $file)
                    <tr>
                        <td>
                            <input type="hidden" name="original_filename[]" value="{{ $file->file }}">
                            {{ $file->file }}
                        </td>
                        <td>
                            {{ $file->name }}
                        </td>
                        <td>
                            <select class="form-control" name="subjects[]" required>
                                <option value="0">Seleziona</option>
                                <option value="new">Crea Nuovo</option>
                                @foreach($order->subjects as $subject)
                                    <option value="{{ $subject->id }}">{{ $subject->name }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </x-larastrap::form>
</x-larastrap::modal>

resources/views/order/modal.blade.php
<x-larastrap::modal size="xl">
    <?php $pacts = App\Pact::orderBy('created_at', 'desc')->get() ?>

    @if($pacts->isEmpty())
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                    Prima di creare un nuovo Ordine devi avere almeno un Patto di riferimento.
                </div>
            </div>
        </div>
    @else
        <x-larastrap::form :method="$order ? 'PUT' : 'POST'" :action="$order ? route('order.update', $order->id) : route('order.store')" :obj="$order" enctype="multipart/form-data">
            <x-larastrap::date name="start" label="Apertura" required />
            <x-larastrap::date name="end" label="Chiusura" required />

            @if($order)
                <x-larastrap::field label="Scarica GDXP">
                    <a href="{{ route('api.order', $order->uuid) }}" class="btn btn-light" target="_blank">Listino Aggregato</a>
                </x-larastrap::field>

                <x-larastrap::field label="Aggregazione">
                    <a href="#" class="btn btn-light async-modal" data-modal-url="{{ route('order.details', $order->id) }}">Vedi Prenotazioni Aggregate</a>
                </x-larastrap::field>
            @endif

            <hr>

            <div class="form-group row" id="order_edit">
                <div class="col-sm-2">
                    <h4>
                        Patti
                    </h4>

                    @foreach($currentuser->accessiblePacts() as $pact)
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="pacts[]" value="{{ $pact->id }}" id="pact-{{ $pact->id }}" {{ $order && $order->pacts()->where('pact_id', $pact->id)->count() != 0 ? 'checked' : '' }}>
                            <label class="form-check-label" for="pact-{{ $pact->id }}">{{ $pact->name }}</label>
                        </div>
                    @endforeach
                </div>

                <div class="col-sm-5">
                    <h4>
                        Listini Fornitori
                    </h4>

                    @if(is_null($order))
                        <div class="alert alert-info mb-3">
                            Se non viene caricato qui nessun listino GDXP, viene utilizzato quello di default per il fornitore.
                        </div>
                    @endif

                    <div id="suppliers">
                        @if($order)
                            @foreach($order->suppliers as $supplier)
                                <div class="form-group row" data-supplier-id="{{ $supplier->id }}">
                                    <input type="hidden" name="suppliers[]" value="{{ $supplier->id }}">
                                    <label class="col-sm-4 col-form-label">{{ $supplier->name }}</label>
                                    <div class="col-sm-8">
                                        <input type="file" class="form-control" name="products_file_{{ $supplier->id }}">
                                        @if($supplier && $supplier->gdxpLastUpdate())
                                            <small class="form-text text-muted">
                                                Ultimo aggiornamento: {{ date('d/m/Y H:i', $supplier->gdxpLastUpdate()) }} - <a href="{{ route('api.get', $supplier->vat) }}" target="_blank">Vedi</a>
                                            </small>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        @endif

                        <div class="form-group row hidden template" data-supplier-id="">
                            <input type="hidden" name="suppliers[]" value="">
                            <label for="name" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <input type="file" class="form-control" name="products_file_">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-5">
                    <h4>
                        Prenotazioni
                    </h4>

                    <div id="subjects">
                        @if($order)
                            <input type="hidden" name="order_id" value="{{ $order->id }}">

                            <div class="form-group row">
                                <label for="name" class="col-sm-4 col-form-label">File Aggregato</label>
                                <div class="col-sm-8">
                                    <input type="file" class="form-control" name="booking_file_multiple">
                                </div>
                            </div>

                            <hr>

                            @foreach($order->subjects as $subject)
                                <div class="form-group row" data-subject-id="{{ $subject->id }}">
                                    <input type="hidden" name="subjects[]" value="{{ $subject->id }}">
                                    <label class="col-sm-4 col-form-label">{{ $subject->name }}</label>
                                    <div class="col-sm-8">
                                        <input type="file" class="form-control" name="booking_file_{{ $subject->id }}">
                                        @if($subject->gdxpLastUpdate())
                                            <small class="form-text text-muted">
                                                Ultimo aggiornamento: {{ date('d/m/Y H:i', $subject->gdxpLastUpdate()) }}
                                            </small>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        @endif

                        <div class="form-group row hidden template" data-subject-id="">
                            <input type="hidden" name="subjects[]" value="">
                            <label for="name" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <input type="file" class="form-control" name="booking_file_">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </x-larastrap::form>
    @endif
</x-larastrap::modal>